<?php

add_ux_builder_shortcode( 'button', array(
	'name'      => __( 'Button' ),
	'category'  => __( 'Content' ),
	'template'  => uxf_builder_template( 'button.html' ),
    'thumbnail' => get_template_directory_uri() . '/inc/builder/shortcodes/thumbnails/button.svg',
	'info'      => '{{ text }}',
	'inline'    => true,
	'wrap'      => false,
	'priority'  => 1,
    'styles' => array(
      'hovercss' => UXF_URL . 'assets/css/hover.min.css',
      'ihovercss' => UXF_URL . 'assets/css/ihover.min.css'
    ),
	'presets'   => array(
		array(
			'name'      => __( 'Simple', 'ux-builder' ),
			'thumbnail' => get_template_directory_uri() . '/inc/builder/shortcodes/thumbnails/button-simple.svg',
			'content'   => '[button text="Click me!"]',
		),
		array(
			'name'      => __( 'Round', 'ux-builder' ),
			'thumbnail' => get_template_directory_uri() . '/inc/builder/shortcodes/thumbnails/button-round.svg',
			'content'   => '[button text="Click me!" radius="10"]',
		),
		array(
			'name'      => __( 'Circle', 'ux-builder' ),
			'thumbnail' => get_template_directory_uri() . '/inc/builder/shortcodes/thumbnails/button-circle.svg',
			'content'   => '[button text="Click me!" radius="99"]',
		),
		array(
			'name'      => __( 'Outline', 'ux-builder' ),
			'thumbnail' => get_template_directory_uri() . '/inc/builder/shortcodes/thumbnails/button-outline.svg',
			'content'   => '[button text="Click me!" style="outline"]',
		),
		array(
			'name'      => __( 'Outline Round', 'ux-builder' ),
			'thumbnail' => get_template_directory_uri() . '/inc/builder/shortcodes/thumbnails/button-outline-round.svg',
			'content'   => '[button text="Click me!" style="outline" radius="10"]',
		),
		array(
			'name'      => __( 'Outline Circle', 'ux-builder' ),
			'thumbnail' => get_template_directory_uri() . '/inc/builder/shortcodes/thumbnails/button-outline-circle.svg',
			'content'   => '[button text="Click me!" style="outline" radius="99"]',
		),
		array(
			'name'      => __( 'Simple Link', 'ux-builder' ),
			'thumbnail' => get_template_directory_uri() . '/inc/builder/shortcodes/thumbnails/button-link.svg',
			'content'   => '[button text="Click me!"  style="link"]',
		),
		array(
			'name'      => __( 'Underline', 'ux-builder' ),
			'thumbnail' => get_template_directory_uri() . '/inc/builder/shortcodes/thumbnails/button-underline.svg',
			'content'   => '[button text="Click me!"  style="underline"]',
		),
		array(
			'name'      => __( 'CTA - Small', 'ux-builder' ),
			'thumbnail' => get_template_directory_uri() . '/inc/builder/shortcodes/thumbnails/button-call-to-action.svg',
			'content'   => '[button text="Click me!" style="shade" depth="3" depth_hover="5" radius="5"]',
		),
		array(
			'name'      => __( 'CTA - Large', 'ux-builder' ),
			'thumbnail' => get_template_directory_uri() . '/inc/builder/shortcodes/thumbnails/button-call-to-action-large.svg',
			'content'   => '[button text="Click me!" style="shade" size="larger" depth="4" depth_hover="5" radius="10"]',
		),
	),
	'options'   => array(
		'text'             => array(
			'type'       => 'textfield',
			'holder'     => 'button',
			'heading'    => 'Text',
			'param_name' => 'text',
			'focus'      => 'true',
			'value'      => 'Button',
			'default'    => '',
		),
		'letter_case'      => array(
			'type'    => 'radio-buttons',
			'heading' => 'Letter Case',
			'default' => '',
			'options' => array(
				''          => array( 'title' => 'ABC' ),
				'lowercase' => array( 'title' => 'Abc' ),
			),
		),
		'layout_options'   => array(
			'type'    => 'group',
			'heading' => 'Layout',
			'options' => array(
				'color'       => array(
					'type'    => 'select',
					'heading' => 'Color',
					'default' => 'primary',
					'options' => array(
						'primary'   => 'Primary',
						'secondary' => 'Secondary',
						'alert'     => 'Alert',
						'success'   => 'Success',
						'white'     => 'White',
						'custom'     => 'Custom',
					),
				),
				'style'       => array(
					'type'    => 'select',
					'heading' => 'Style',
					'default' => '',
					'options' => array(
						''          => 'Default',
						'outline'   => 'Outline',
						'link'      => 'Simple',
						'underline' => 'Underline',
						'shade'     => 'Shade',
						'bevel'     => 'Bevel',
						'gloss'     => 'Gloss',
					),
				),
				'text_color' => array(
					'conditions' => 'color == "custom"',
					'type'     => 'colorpicker',
					'heading'  => __( 'Text Color', 'flatsome' ),
					'default' => '',
					'format'   => 'rgb',
					'helpers'  => require( get_template_directory() . '/inc/builder/shortcodes/helpers/colors.php' ),
				),
				'bg_color' => array(
					'conditions' => 'color == "custom"',
					'type'     => 'colorpicker',
					'heading'  => __( 'BG Color', 'flatsome' ),
					'default' => '',
					'format'   => 'rgb',
					'helpers'  => require( get_template_directory() . '/inc/builder/shortcodes/helpers/colors.php' ),
				),
                'bg_gradient' => array(
                    'conditions' => 'color == "custom"',
                    'type'     => 'colorpicker',
                    'heading'  => __( 'BG Gradient', 'flatsome' ),
                    'default' => '',
                    'format'   => 'rgb',
                    'helpers'  => require( get_template_directory() . '/inc/builder/shortcodes/helpers/colors.php' ),
                ),
                'bg_gradient_to' => array(
                  'conditions' => 'bg_gradient',
                  'type' => 'radio-buttons',
                  'heading' => 'Gradient To',
                  'full_width' => true,
                  'default' => 'left',
                  'options' => array(
                    'top'   => array( 'title' => 'Top'),
                    'left'   => array( 'title' => 'Left'),
                    'right'   => array( 'title' => 'Right'),
                    'bottom'   => array( 'title' => 'Bottom'),
                    ),
                  ),
				'border' => array(
					'type' => 'scrubfield',
					'heading' => 'Border',
					'default' => '',
					'unit' => 'px',
					'min' => 0,
					'max' => 50,
				),
				'border_style' => array(
					'conditions' => 'border',
					'type' => 'radio-buttons',
					'heading' => 'Border Style',
					'full_width' => true,
					'default' => '',
					'options' => array(
						'' => array( 'title' => 'None', 'icon' => 'dashicons-no-alt', ),
						'solid'   => array( 'title' => 'Solid'),
						'dashed'  => array( 'title' => 'Dashed'),
						'dotted'  => array( 'title' => 'Dotted'),
					),
				),
				'border_color' => array(
					'conditions' => 'border',
					'type'     => 'colorpicker',
					'heading'  => __( 'Border Color', 'flatsome' ),
					'default' => '',
					'format'   => 'rgb',
					'helpers'  => require get_template_directory() . '/inc/builder/shortcodes/helpers/colors.php',
				),
				'size'        => array(
					'type'    => 'select',
					'heading' => 'Size',
					'options' => require get_template_directory() . '/inc/builder/shortcodes/values/sizes.php',
				),
				'weight'      => array(
					'type' => 'radio-buttons',
					'heading' => 'Weight',
					'full_width' => true,
					'default' => '',
					'options' => array(
						''          => array( 'title' => 'Bold' ),
						'normal' => array( 'title' => 'Normal' ),
						'thin' => array( 'title' => 'Thin' ),
						'italic' => array( 'title' => 'Italic' ),
					),
				),
				'letter_spacing'      => array(
					'type'    => 'slider',
					'heading' => __( 'Letter Spacing', 'flatsome' ),
					'default' => '',
					'max'     => 30,
					'min'     => 0,
				),
				'animate'     => array(
					'type'    => 'select',
					'heading' => 'Animate',
					'default' => 'none',
					'options' => require get_template_directory() . '/inc/builder/shortcodes/values/animate.php',
				),
				'padding'     => array(
					'type'       => 'margins',
					'heading'    => 'Padding',
					'full_width' => true,
					'min'        => 0,
					'max'        => 200,
					'step'       => 1,
				),
				'radius'      => array(
					'type'    => 'slider',
					'class'   => '',
					'heading' => 'Radius',
					'default' => '0',
					'max'     => '99',
					'min'     => '0',
				),
				'depth'       => array(
					'type'    => 'slider',
					'class'   => '',
					'heading' => 'Depth',
					'default' => '0',
					'max'     => '5',
					'min'     => '0',
				),
				'depth_hover' => array(
					'type'       => 'slider',
					'class'      => '',
					'heading'    => 'Depth :hover',
					'param_name' => 'depth_hover',
					'default'    => '0',
					'max'        => '5',
					'min'        => '0',
				),
				'expand'      => array(
					'type'    => 'checkbox',
					'heading' => 'Expand',
				),
                'tooltip'             => array(
                    'type'       => 'textfield',
                    'heading'    => 'Tooltip',
                    'default'    => '',
                ),
			),
		),
		'icon_options'     => array(
			'type'    => 'group',
			'heading' => 'Icon',
			'options' => array(
				'icon'        => array(
					'type'    => 'select',
					'heading' => 'Icon',
					'options' => require UXF_DIR . '/inc/builder/shortcodes/values/icons.php',
				),
                'icon_custom' => array(
					'conditions' => 'icon == "custom"',
                    'type'       => 'textfield',
                    'heading'    => 'Icon Class',
                ),
                'icon_size' => array(
                    'type'       => 'scrubfield',
                    'heading'    => 'Icon Size',
					'min' => 0,
					'unit' => 'px',
                ),
				'icon_pos'    => array(
					'conditions' => 'icon',
					'type'       => 'select',
					'heading'    => 'Position',
					'options'    => array(
						''     => 'Right',
						'left' => 'Left',
					),
				),
				'icon_reveal' => array(
					'conditions' => 'icon',
					'type'       => 'select',
					'heading'    => 'Visibility',
					'options'    => array(
						''     => 'Always visible',
						'true' => 'Visible on hover',
					),
				),
                'icon_hover'        => array(
					'conditions' => 'icon',
                    'type'    => 'select',
                    'heading' => 'Icon Hover',
					'options' => require UXF_DIR . '/inc/builder/shortcodes/values/ihover.php',
                ),
			),
		),
		'hover_options' => require UXF_DIR . '/inc/builder/shortcodes/commons/hover.php',
		'onclick_options'     => array(
			'type'    => 'group',
			'heading' => 'OnClick',
			'options' => array(
                'onclick'    => array(
                    'type'    => 'textfield',
                    'heading' => 'OnClick',
                ),
			),
		),
		'link_options'     => require get_template_directory() . '/inc/builder/shortcodes/commons/links.php',
		'advanced_options' => require get_template_directory() . '/inc/builder/shortcodes/commons/advanced.php',
	),
) );
