<?php
// HoverCSS Control
return array(
      'type' => 'group',
      'heading' => __( 'Hover CSS' ),
      'options' => array(
		'hover'     => array(
			'type'    => 'select',
			'heading' => 'Hover',
			'default' => '',
			'options' => array(
				'' => 'None',
                'blick' => 'Blick',
                'wave' => 'Wave',
                'neon' => 'Neon',
                //Old Hover
                'border-1' => 'Hover Border 1',
                'border-2' => 'Hover Border 2',
                'border-3' => 'Hover Border 3',
                'border-4' => 'Hover Border 4',
                'border-5' => 'Hover Border 5',
                'border-6' => 'Hover Border 6',
                'border-7' => 'Hover Border 7',
                'border-8' => 'Hover Border 8',
                'border-9' => 'Hover Border 9',
                'border-10' => 'Hover Border 10',
                'swipe-overlay' => 'Swipe Overlay',
                'swipe-overlay-out' => 'Swipe Overlay Out',
                'increase-letter-space' => 'Increase Letter Space',
                'flip-horizontal' => 'Flip Horizontal',
                'flip-vertical' => 'Flip Vertical',
                'bg-hide' => 'Background Hide',
                'radial-out' => 'Radial Out',
                'radial-in' => 'Radial In',
                'slide-down' => 'Slide Down',
                'slide-up' => 'Slide Up',
                'slide-left' => 'Slide Left',
                'slide-right' => 'Slide Right',
                'radius-increase' => 'Radius Increase',
                'radius-decrease' => 'Radius Decrease',
                'border-dashed' => 'Border Dashed',
                'border-dotted' => 'Border Dotted',
                'opacity-increase' => 'Opacity Increase',
                'opacity-decrease' => 'Opacity Decrease',
                'grayscale-increase' => 'Grayscale Increase',
                'grayscale-decrease' => 'Grayscale Decrease',
                'blur-in' => 'Blur In',
                'blur-out' => 'Blur Out',
                'bg-color' => 'Background Color',
                'text-color' => 'Text Color',
                'border-color' => 'Border Color',
                'border-text-color' => 'Border Text Color',
                'shadow-increase' => 'Shadow Increase',
                'shadow-decrease' => 'Shadow Decrease',
                'shadow-float' => 'Shadow Float',
                'scale-increase' => 'Scale Increase',
                'scale-decrease' => 'Scale Decrease',
                'float-down' => 'Float Down',
                'float-up' => 'Float Up',
                'float-left' => 'Float Left',
                'float-right' => 'Float Right',
                'button-rotate' => 'Button Rotate',
                'button-rotate-grow' => 'Button Rotate Grow',
                'button-rotate-shrink' => 'Button Rotate Shrink',
                'skew-horizontal' => 'Skew Horizontal',
                'skew-vertical' => 'Skew Vertical',
			),
		),
    ),
);